# Generated by Django 2.0.6 on 2018-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('who', models.CharField(max_length=200)),
                ('to_date', models.DateTimeField()),
                ('from_date', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
