# Generated by Django 2.0.6 on 2018-07-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
