# Generated by Django 2.0.6 on 2018-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='filtered_image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/filtered'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='who',
            field=models.TextField(),
        ),
    ]
